import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const avenirBlack = localFont({
  src: "./fonts/AvenirBlack.woff2",
  variable: "--font-avenir-black",
  weight: "100 900",
});

const avenirRegular = localFont({
  src: "./fonts/AvenirRegular.woff2",
  variable: "--font-avenir-regular",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${avenirBlack.variable} ${avenirRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
